[package]
name = "tgt-intro-woox"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13.1", features = ["blocking", "query", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tungstenite = "0.28.0"
url = "2.5.8"
